@import "jquery.min.js";
@import "popper.js";
@import "bootstrap.min.js";
// @import "../../node_modules/fullpage.js/vendors/easings.js";
// @import "../../node_modules/fullpage.js/vendors/scrolloverflow.js";
// @import "../../node_modules/fullpage.js/dist/fullpage.js";
// @import "../../node_modules/particles.js/particles.js";
// @import "jquery.sticky.js";
@import "letterfx.js";
@import "bouncy.js";
@import "slick.js";
@import "custom.js";